add_user:
    path:     /admin/addUser
    defaults: { _controller: AdminBundle:User:addUser }

add_lector:
    path:     /admin/user/lector/add
    defaults: { _controller: AdminBundle:User\Lector:add }

update_lector:
    path:     /admin/user/lector/update/profile
    defaults: { _controller: AdminBundle:User\Lector:update}

show_lector:
    path:     /admin/user/lector/show
    defaults: { _controller: AdminBundle:User\Lector:show}

show_profile_lector:
    path:     /admin/user/lector/show/profile/{userId}
    defaults: { _controller: AdminBundle:User\Lector:showProfile}

edit_profile_lector:
    path:     /admin/user/lector/edit/profile/{userId}
    defaults: { _controller: AdminBundle:User\Lector:editProfile}

filter_lector:
    path:     /admin/user/lector/filter
    defaults: { _controller: AdminBundle:User\Lector:filter}


add_dr:
    path:     /admin/user/dr/add
    defaults: { _controller: AdminBundle:User\Dr:add }

update_dr:
    path:     /admin/user/dr/update/profile
    defaults: { _controller: AdminBundle:User\Dr:update}

show_dr:
    path:     /admin/user/dr/show
    defaults: { _controller: AdminBundle:User\Dr:show}

show_profile_dr:
    path:     /admin/user/dr/show/profile/{userId}
    defaults: { _controller: AdminBundle:User\Dr:showProfile}

edit_profile_dr:
    path:     /admin/user/dr/edit/profile/{userId}
    defaults: { _controller: AdminBundle:User\Dr:editProfile}

filter_dr:
    path:     /admin/user/dr/filter
    defaults: { _controller: AdminBundle:User\Dr:filter}




add_fiche:
    path:     /admin/fiche/add
    defaults: { _controller: AdminBundle:Fiche:add }

update_fiche:
    path:     /admin/fiche/update/profile
    defaults: { _controller: AdminBundle:Fiche:update}

show_fiche:
    path:     /admin/fiche/show
    defaults: { _controller: AdminBundle:Fiche:show}

show_profile_fiche:
    path:     /admin/fiche/show/profile/{ficheId}
    defaults: { _controller: AdminBundle:Fiche:showProfile}

edit_profile_fiche:
    path:     /admin/fiche/edit/profile/{ficheId}
    defaults: { _controller: AdminBundle:Fiche:editProfile}

filter_fiche:
    path:     /admin/fiche/filter
    defaults: { _controller: AdminBundle:Fiche:filter}



add_parent:
    path:     /admin/parent/add
    defaults: { _controller: AdminBundle:User\Parent:add }

update_parent:
    path:     /admin/parent/update/profile
    defaults: { _controller: AdminBundle:User\Parent:update}

show_parent:
    path:     /admin/parent/show
    defaults: { _controller: AdminBundle:User\Parent:show}

show_profile_parent:
    path:     /admin/parent/show/profile/{userId}
    defaults: { _controller: AdminBundle:User\Parent:showProfile}

edit_profile_parent:
    path:     /admin/parent/edit/profile/{userId}
    defaults: { _controller: AdminBundle:User\Parent:editProfile}

filter_parent:
    path:     /admin/parent/filter
    defaults: { _controller: AdminBundle:User\Parent:filter}

add_school:
    path:     /admin/school/add
    defaults: { _controller: AdminBundle:School:add }

update_school:
    path:     /admin/school/update/
    defaults: { _controller: AdminBundle:School:update}

import_school:
    path:     /admin/school/import
    defaults: { _controller: AdminBundle:School:import }

assign_dr_to_school:
    path:     /admin/school/assign_dr
    defaults: { _controller: AdminBundle:School:assignDR }

show_school:
    path:     /admin/school/show
    defaults: { _controller: AdminBundle:School:show}

show_profile_school:
    path:     /admin/school/show/profile/{schoolId}
    defaults: { _controller: AdminBundle:School:showProfile}

edit_school:
    path:     /admin/school/edit/{schoolId}
    defaults: { _controller: AdminBundle:School:editSchool}

filter_school:
    path:     /admin/school/filter
    defaults: { _controller: AdminBundle:School:filter}


add_group:
    path:     /admin/user/group/add
    defaults: { _controller: AdminBundle:User\Group:add }

update_group:
    path:     /admin/user/group/update/profile
    defaults: { _controller: AdminBundle:Group:update}

show_group:
    path:     /admin/user/group/show
    defaults: { _controller: AdminBundle:Group:show}

show_profile_group:
    path:     /admin/group/show/profile/{groupId}
    defaults: { _controller: AdminBundle:Group:showProfile}

edit_profile_group:
    path:     /admin/group/edit/profile/{groupId}
    defaults: { _controller: AdminBundle:Group:editProfile}

filter_group:
    path:     /admin/group/filter
    defaults: { _controller: AdminBundle:Group:filter}

assign_lector_to_group:
    path:     /admin/group/assign_lector
    defaults: { _controller: AdminBundle:Group:assignLector}
    
    