add_user:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

process_uploaded_file:
    path:     /processUploadedFile
    defaults: { _controller: AppBundle:Default:processUploadedFile }
    